<a href="https://colab.research.google.com/github/qq995414/knn/blob/main/knn_homemoney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = np.array([[500.0, 3.0, 0.3], [1000.0, 1.0, 0.6], [750.0, 2.0, 0.3], [600.0, 5.0, 0.2], [1200.0, 1.0, 0.6]])
y = np.array([10000, 9000, 8000, 12000, 8500])
# 標準化,按列轉化，轉化到數據均值為0方差為1的標準分佈內
std_x = StandardScaler()
x_train = std_x.fit_transform(X)
x_train
#std_y = StandardScaler()
#y_train = std_y.fit_transform(Y.reshape(-1, 1))
# 構建線性預測模型
#lr = LinearRegression()
# 模型在歷史數據上進行訓練，Y.reshape(-1,1)將Y變為二維數組，fit函數要求二維數組
#lr.fit(x_train, y_train)
# 使用訓練模型預測新房屋價格
#x_predict = std_x.transform(np.array([[200, 5.0, 10.0]]))
#print(std_y.inverse_transform(lr.predict(x_predict)))

array([[-1.20303331,  0.40089186, -0.5976143 ],
       [ 0.737343  , -0.93541435,  1.19522861],
       [-0.23284516, -0.26726124, -0.5976143 ],
       [-0.81495805,  1.73719807, -1.19522861],
       [ 1.51349353, -0.93541435,  1.19522861]])

In [ ]:
x = np.array([[500.0, 3.0, 0.3], [1000.0, 1.0, 0.6], [750.0, 2.0, 0.3], [600.0, 5.0, 0.2], [1200.0, 1.0, 0.6]])
y = np.array([10000, 9000, 8000, 12000, 8500])
print(x)
print(y)

[[5.0e+02 3.0e+00 3.0e-01]
 [1.0e+03 1.0e+00 6.0e-01]
 [7.5e+02 2.0e+00 3.0e-01]
 [6.0e+02 5.0e+00 2.0e-01]
 [1.2e+03 1.0e+00 6.0e-01]]
[10000  9000  8000 12000  8500]


In [ ]:
std_x = StandardScaler()
x_train = std_x.fit_transform(X)
x_train

array([[-1.20303331,  0.40089186, -0.5976143 ],
       [ 0.737343  , -0.93541435,  1.19522861],
       [-0.23284516, -0.26726124, -0.5976143 ],
       [-0.81495805,  1.73719807, -1.19522861],
       [ 1.51349353, -0.93541435,  1.19522861]])

In [ ]:
std_y = StandardScaler()
y_train = std_y.fit_transform(y.reshape(-1, 1))
y_train

array([[ 0.35355339],
       [-0.35355339],
       [-1.06066017],
       [ 1.76776695],
       [-0.70710678]])

In [ ]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
x_predict = std_x.transform(np.array([[200, 6.0, 0.4]]))
print(std_y.inverse_transform(lr.predict(x_predict)))

[[16368.05555556]]


In [ ]:
 import numpy as np
 import pandas as pd
 from sklearn.linear_model import LinearRegression
 from sklearn.preprocessing import StandardScaler
 from sklearn.neighbors import KNeighborsClassifier
 from sklearn.feature_extraction import DictVectorizer
 from sklearn.tree import DecisionTreeClassifier

In [ ]:
import pandas as pd


In [ ]:
home = pd.read_csv("./home.csv",nrows=7)

In [ ]:
home

money   train  schoo  green
0  10000   500.0    3.0    0.3
1   9000  1000.0    1.0    0.6
2   8000   750.0    2.0    0.3
3  12000   600.0    5.0    0.2
4   8500  1200.0    1.0    0.6
5  15000   250.0    6.0    0.3
6   9000   800.0    4.0    0.2

NameError: ignored

In [ ]:
std_x = StandardScaler()
x_train = std_x.fit_transform(x)
x_train

std_y = StandardScaler()
y_train = std_y.fit_transform(y)
y_train

array([[-0.78118519, -0.07905694, -0.3592106 ],
       [ 0.92765741, -1.18585412,  1.52664507],
       [ 0.07323611, -0.63245553, -0.3592106 ],
       [-0.43941667,  1.02774024, -0.98782916],
       [ 1.61119445, -1.18585412,  1.52664507],
       [-1.63560649,  1.58113883, -0.3592106 ],
       [ 0.24412037,  0.47434165, -0.98782916]])

In [ ]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
x_predict = std_x.transform(100,5.0,10.0)
print(x_predict)

TypeError: ignored